# Generated by Django 5.0.2 on 2024-03-07 10:04

import django.core.validators
import django.db.models.deletion
import mobiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('samsung', 'Samsung'), ('apple', 'Apple'), ('xiaomi', 'Xiaomi'), ('nokia', 'Nokia')], max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Value must be greater than or equal to 0.0'), django.core.validators.MaxValueValidator(5.0, message='Value must be less than or equal to 5.0')])),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=mobiles.models.mobile_img_directory_path)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mobiles.mobile')),
            ],
        ),
    ]
