# Generated by Django 5.0.2 on 2024-02-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('samsung', 'Samsung'), ('apple', 'Apple'), ('xiaomi', 'Xiaomi'), ('nokia', 'Nokia')], max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('price', models.PositiveBigIntegerField()),
            ],
        ),
    ]
