# Generated by Django 5.0.2 on 2024-03-04 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileimage',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mobiles.mobile'),
        ),
    ]
