# Generated by Django 5.0.2 on 2024-02-29 15:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Value must be greater than or equal to 0.0'), django.core.validators.MaxValueValidator(5.0, message='Value must be less than or equal to 100.0')]),
        ),
    ]
