# Generated by Django 5.0.2 on 2024-04-06 08:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_alter_mobile_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
