# Generated by Django 5.0.2 on 2024-04-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_mobile_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='sells',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
