# Generated by Django 5.0.2 on 2024-04-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
