# Generated by Django 5.0.2 on 2024-03-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_in_cart',
        ),
    ]
