# Generated by Django 5.0.2 on 2024-04-16 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0007_delete_review'),
        ('orders', '0003_alter_order_unique_together_alter_order_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_purchased',
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobiles.mobile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PurchasedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobiles.mobile')),
                ('purchased_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.purchasedorder')),
            ],
        ),
    ]
