# Generated by Django 5.0.2 on 2024-04-16 11:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_is_purchased_alter_order_mobile_and_more'),
        ('wallets', '0002_alter_transaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedorder',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='wallets.transaction'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='purchasedorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
